USE prueba;
CREATE TABLE users (
  id_user INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR (110) NOT NULL,
  user_identification VARCHAR (50) NOT NULL UNIQUE,
  email VARCHAR (110) DEFAULT NULL UNIQUE,
  telephone VARCHAR (30) DEFAULT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE book (
  isbn VARCHAR (20) NOT NULL PRIMARY KEY,
  title VARCHAR (80) NOT NULL,
  publication_year  YEAR  NOT NULL,
  author VARCHAR (150)  NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE loans (
  id_loans INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_user INT DEFAULT NULL,
  isbn VARCHAR (20) DEFAULT NULL,
  loan_date DATE NOT NULL,
  return_date DATE DEFAULT NULL,
  status ENUM ('delivered', 'delayed', 'active') DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (isbn) REFERENCES book(isbn) ON DELETE SET NULL ON UPDATE CASCADE 
);